clothesshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change_quantity/', views.cart_change_quantity, name='cart_change_quantity'),
    path('cart_change_size/', views.cart_change_size, name='cart_change_size'),
    path('cart_change_delivery/', views.cart_change_delivery, name='cart_change_delivery'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

clothesshop/clothes/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.catalog, name='catalog'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit_product/<slug:product_slug>', views.edit_product, name='edit_product'),
    path('delete_product/<slug:product_slug>', views.delete_product, name='delete_product'),
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='catalog_by_category'),
    path('product/<slug:product_slug>', views.product, name='product'),
]

clothesshop/clothesshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('clothes.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clothesshop/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

clothesshop/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('cart/', views.cart, name='cart'),
    path('user_orders/', views.user_orders, name='user_orders'),
    path('manage_users/', views.manage_users, name='manage_users'),
    path('edit_user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('statistics/', views.statistics, name='statistics'),
    path('delete_profile/', views.delete_profile, name='delete_profile'),
    path('logout/', views.logout, name='logout'),
]

clothesshop/templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    {% block css %}{% endblock %}
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.6.0/css/fontawesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.6.0/css/all.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">

</head>
<body>
<header class="p-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="{% url 'main:index' %}"
               class="d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis text-decoration-none">
                <i class="fa-brands fa-slack fa-spin"></i>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'main:about' %}" class="nav-link px-2 link-body-emphasis">Overview</a></li>
                <li><a href="{% url 'catalog:catalog' %}" class="nav-link px-2 link-body-emphasis">Catalog</a></li>
                <li><a href="#" class="nav-link px-2 link-body-emphasis">Album</a></li>
                <li><a href="#" class="nav-link px-2 link-body-emphasis">Information</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'catalog:search' %}"
                  method="get">
                <input type="search" class="form-control" name="q" placeholder="Search..." aria-label="Search">
                <button type="submit" class="btn btn-outline-secondary">
                    <i class="bi bi-search"></i>
                </button>
            </form>

            <div class="shopping-cart"><a href="{% url 'users:cart' %}"><i class="bi bi-cart"></i></a></div>

            <div class="dropdown text-end">
                <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="{% static 'img/profile.png' %}" alt="mdo" width="32" height="32" class="rounded-circle">
                </a>
                <ul class="dropdown-menu text-small">
                    {% if not user.is_authenticated %}
                    <li><a class="dropdown-item" href="{% url 'user:login' %}">Login</a></li>
                    {% elif user.is_superuser or user.is_staff %}
                    <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin panel</a></li>
                    <li><a class="dropdown-item" href="{% url 'user:manage_users' %}">Users Management</a></li>
                    <li><a class="dropdown-item" href="{% url 'user:profile' %}">Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'user:user_orders' %}">My orders</a></li>
                    <li><a class="dropdown-item" href="{% url 'user:statistics' %}">Statistics</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'user:logout' %}">Sign out</a></li>
                    {% else %}
                    <li><a class="dropdown-item" href="{% url 'user:profile' %}">Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'user:user_orders' %}">My orders</a></li>
                    <li><a class="dropdown-item" href="{% url 'user:profile' %}">Settings</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'user:logout' %}">Sign out</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</header>

{% include 'includes/notifications.html' %}
{% block content %}
{% endblock %}

<footer class="footer">
    <div class="column">
        <h4>Contact</h4>
        <p><strong>Adress: </strong> Voronezh, University Square 7</p>
        <p><strong>Phone: </strong> 8-961-109-51-55</p>
        <p><strong>Hours: </strong> 10:00 - 18:00, Mon - Sat</p>
        <div class="follow">
            <h4>Follow us</h4>
            <div class="icon">
                <i class="fab fa-facebook-f"></i>
                <i class="fab fa-instagram"></i>
                <i class="fab fa-youtube"></i>
                <i class="fab fa-twitter"></i>
                <i class="fab fa-telegram"></i>
            </div>
        </div>
    </div>

    <div class="column">
        <h4>Information</h4>
        <a href="">About us</a>
        <a href="">Delivery information</a>
        <a href="">Privacy Policy</a>
        <a href="">Terms & Conditions</a>
        <a href="">Contact us</a>
    </div>

    <div class="column">
        <h4>My Account</h4>
        <a href="">Sign in</a>
        <a href="">View Cart</a>
        <a href="">My wishlist</a>
        <a href="">Track my order</a>
        <a href="">Help</a>
    </div>

    <div class="column install">
        <h4>Install app</h4>
        <p>From App Store or Google Play</p>
        <div class="row download">
            <i class="fa-brands fa-app-store"></i>
            <i class="fa-brands fa-google-play"></i>
        </div>
        <p>Secured Payment Getaways</p>
        <div class="row payment">
            <i class="fa-brands fa-cc-visa"></i>
            <i class="fa-brands fa-cc-mastercard"></i>
            <i class="fa-brands fa-cc-paypal"></i>
            <i class="fa-brands fa-cc-apple-pay"></i>
        </div>
    </div>

    <div class="copyright">
        <p>&copy; 2024 G-Shop, Inc</p>
    </div>
</footer>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="{% static 'js/jquery-ajax.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>