clothesshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change_quantity/', views.cart_change_quantity, name='cart_change_quantity'),
    path('cart_change_size/', views.cart_change_size, name='cart_change_size'),
    path('cart_change_delivery/', views.cart_change_delivery, name='cart_change_delivery'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

clothesshop/clothes/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.catalog, name='catalog'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit_product/<slug:product_slug>', views.edit_product, name='edit_product'),
    path('delete_product/<slug:product_slug>', views.delete_product, name='delete_product'),
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='catalog_by_category'),
    path('product/<slug:product_slug>', views.product, name='product'),
]

clothesshop/clothesshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('clothes.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clothesshop/clothes/models.py
from django.db import models
from django.utils.text import slugify


class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Name')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table = 'category'
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Products(models.Model):
    brand = models.CharField(max_length=150, unique=False, verbose_name='Brand')
    name = models.CharField(max_length=150, unique=True, verbose_name='Name')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Description')
    image = models.ImageField(upload_to='clothes_images', blank=True, null=True, verbose_name='Image')
    price = models.DecimalField(default=0, max_digits=10, decimal_places=0, verbose_name='Price')
    discount = models.DecimalField(default=0, max_digits=2, decimal_places=0, verbose_name='Discount, %')
    color = models.CharField(max_length=50, blank=True, null=True, verbose_name='Color')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Category')

    class Meta:
        db_table = 'product'
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        ordering = ['brand']

    def __str__(self):
        return f"{self.brand} {self.name}"

    def display_id(self):
        return f"{self.id:05}"

    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100)
        return self.price

    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(f'{self.brand}-{self.name}')
            slug = base_slug
            counter = 1
            while Products.objects.filter(slug=slug).exists():
                slug = f'{base_slug}-{counter}'
                counter += 1
            self.slug = slug
        super().save(*args, **kwargs)

class ProductImages(models.Model):
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE, verbose_name='Product', related_name='images')
    image = models.ImageField(upload_to='clothes_images', blank=True, null=True, verbose_name='Image')

    class Meta:
        db_table = 'product_image'
        verbose_name = 'Product Image'
        verbose_name_plural = 'Product Images'

    def __str__(self):
        return f"Image for {self.product.brand} {self.product.name}"


class Sizes(models.Model):
    size = models.CharField(max_length=10, unique=True, verbose_name='Size')

    class Meta:
        db_table = 'size'
        verbose_name = 'Size'
        verbose_name_plural = 'Sizes'

    def __str__(self):
        return f"{self.size}"

class ProductSizes(models.Model):
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE, verbose_name='Product', related_name='sizes')
    size = models.ForeignKey(to=Sizes, on_delete=models.CASCADE, verbose_name='Size', related_name='products')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Quantity')

    class Meta:
        db_table = 'product_size'
        verbose_name = 'Product Size'
        verbose_name_plural = 'Product Sizes'
        ordering = ['id']

    def __str__(self):
        return f"{self.product.name} {self.size} {self.quantity}"

clothesshop/clothes/forms.py
from django import forms
from .models import Products, ProductImages


class ProductsForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = ['brand', 'name', 'description', 'image', 'price', 'discount', 'color', 'category']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Product Name'}),
            'brand': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Brand'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Price, RUB'}),
            'discount': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Discount, %'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}),
        }

class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = ['brand', 'name', 'description', 'image', 'price', 'discount', 'color', 'category']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Product Name'}),
            'brand': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Brand'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Price, RUB'}),
            'discount': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Discount, %'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}),
        }


class ProductImageForm(forms.ModelForm):
    image = forms.ImageField()

    class Meta:
        model = ProductImages
        fields = ['image']

clothesshop/clothes/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import Paginator
from django.db.models import Min, Max
from django.shortcuts import render, redirect

from .forms import ProductsForm, ProductEditForm
from .models import Products, ProductImages, ProductSizes
from .utils import q_search


def catalog(request, category_slug=None):
    page = request.GET.get('page', 1)
    on_sale = request.GET.get('on_sale', None)
    order_by = request.GET.get('order_by', None)
    query = request.GET.get('q', None)

    price_range = Products.objects.aggregate(min_price=Min('price'), max_price=Max('price'))
    min_price = price_range['min_price']
    max_price = price_range['max_price']

    selected_min_price = request.GET.get('min_price', min_price)
    selected_max_price = request.GET.get('max_price', max_price)

    if category_slug == 'all-products':
        products = Products.objects.all()
    elif query:
        products = q_search(query)
    elif category_slug == None:
        products = Products.objects.all()
        category_slug = 'all-products'
    else:
        products = Products.objects.filter(category__slug=category_slug)

    if on_sale:
        products = products.filter(discount__gt=0)

    products = products.filter(price__gte=selected_min_price, price__lte=selected_max_price)

    if order_by and order_by != 'default':
        products = products.order_by(order_by)

    form = ProductsForm()
    paginator = Paginator(products, 4)
    current_page = paginator.page(page)

    context = {
        'title': 'G-Shop | Catalog',
        'products': current_page,
        'slug_url': category_slug,
        'form': form,
        'min_price': min_price,
        'max_price': max_price,
        'selected_min_price': selected_min_price,
        'selected_max_price': selected_max_price,
    }

    return render(request, 'clothes/catalog.html', context)


def product(request, product_slug):
    product = Products.objects.get(slug=product_slug)
    sizes = ProductSizes.objects.filter(product=product)
    form = ProductEditForm(instance=product)

    context = {
        'title': 'G-Shop | Product',
        'product': product,
        'sizes': sizes,
        'form': form,
    }

    return render(request, 'clothes/product.html', context=context)

@login_required
@user_passes_test(lambda u: u.is_superuser)
def add_product(request):
    if request.method == 'POST':
        form = ProductsForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('catalog:catalog')
        else:
            form = ProductsForm()

    context = {
        'title': 'G-Shop | Add Product',
        'form': form,
    }

    return redirect('catalog:catalog', context)

@login_required
@user_passes_test(lambda u: u.is_superuser)
def edit_product(request, product_slug):
    product = Products.objects.get(slug=product_slug)

    if request.method == 'POST':
        form = ProductEditForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            product = form.save()
            if request.FILES.getlist('new_images'):
                for image in request.FILES.getlist('new_images'):
                    ProductImages.objects.create(product=product, image=image)
            return redirect('catalog:product', product_slug)
    else:
        form = ProductEditForm(instance=product)

    context = {
        'title': 'G-Shop | Edit Product',
        'form': form,
        'product': product,
    }

    return redirect('catalog:product', context)

@login_required
@user_passes_test(lambda u: u.is_superuser)
def delete_product(request, product_slug):
    product = Products.objects.get(slug=product_slug)

    if request.method == 'POST':
        product.delete()
        messages.success(request, f'Product "{product.name}" deleted successfully')
        return redirect('catalog:catalog')

clothesshop/clothes/templates/clothes/catalog.html
{% extends 'layout.html' %}
{% load static %}
{% load clothes_tags%}

{% block css %}
<link rel="stylesheet" href="{% static 'css/catalog.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/nouislider@15.6.0/dist/nouislider.min.css">

{% endblock %}

{% block title %}{{title}}{% endblock %}

{% block content %}

<section class="catalog-header">
    <h2>Clothes catalog</h2>
    <p>Modern beauty</p>
</section>

<section class="product-filtering">
    <div class="dropdown mb-2">
        <button class="btn dropdown-toggle category-button" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">Category</button>
        <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
            {% tag_categories as categories %}
            {% for category in categories %}
            <li><a class="dropdown-item text-white" href="{% url 'catalog:catalog_by_category' category.slug %}">{{category.name}}</a>
            </li>
            {% endfor %}
        </ul>
    </div>

    <button id="filterButton" class="btn dropdown-toggle filter-button">Filters</button>

    <div id="filterMenu" class="dropdown-menu bg-black">
        <form action="{% if request.GET.q %}{% url 'catalog:search' %}{% else %}{% url 'catalog:catalog_by_category' slug_url %}{% endif %}"
              method="get" class="form">
            <div class="mx-3 mt-3">
                <label for="price-range" class="text-white filter-price">Price</label>
                <div id="price-range" class="price-slider"></div>
                <div class="d-flex justify-content-between text-white">
                    <span id="price-min">{{ min_price }}</span><span id="price-max">{{ max_price }}</span>
                </div>
                <input type="hidden" name="min_price" id="min-price" value="{{ selected_min_price }}">
                <input type="hidden" name="max_price" id="max-price" value="{{ selected_max_price }}">
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on"
                       {% if request.GET.on_sale == 'on' %}checked{% endif %}>
                <label class="form-check-label" for="flexCheckDefault">
                    Discounted clothes
                </label>
            </div>

            <div class="form-check">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default"
                       {% if not request.GET.order_by or request.GET.order_by == 'default' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault1">
                    By default
                </label>
            </div>

            <div class="form-check">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price"
                       {% if request.GET.order_by == 'price' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault2">
                    From cheap to expensive
                </label>
            </div>

            <div class="form-check">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price"
                       {% if request.GET.order_by == '-price' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault3">
                    From expensive to cheap
                </label>
            </div>

            <button type="submit" class="btn-apply">Apply</button>
        </form>
    </div>

    {% if user.is_superuser or user.is_stuff %}
    <div class="admin-controls">
        <button class="btn btn-success" id="add-product-btn" data-bs-toggle="modal" data-bs-target="#addProductModal">
            + Add
        </button>
    </div>
    <div class="modal fade" id="addProductModal" tabindex="-1" aria-labelledby="addProductModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addProductModalLabel">Add product</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" enctype="multipart/form-data" id="add-product-form"
                      action="{% url 'catalog:add_product' %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        <h6>Add Product</h6>
                        {{ form.as_p }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endif %}
</section>


<section class="catalog-products">
    <div class="catalog-container">
        {% for product in products %}
        <div class="catalog-product">
            {% if product.image %}
            <a class="product-link" href="{% url 'catalog:product' product.slug %}">
                <div class="product-image">
                    <img src="{{ product.image.url }}" alt="">
                    {% if product.discount %}
                    <div class="discount-label">Sale {{ product.discount }}%</div>
                    {% endif %}
                </div>
                {% endif %}
                <div class="product-info">
                    <span>{{ product.brand }}</span>
                    <h5>{{ product.name }}</h5>
                    {% if product.discount %}
                    <div class="discount">
                        <h4>{{ product.sell_price }} RUB</h4>
                        <h4 class="original-price">{{ product.price }} RUB</h4>
                    </div>
                    {% else %}
                    <h4>{{ product.price }} RUB</h4>
                    {% endif %}
                </div>
                <a href="#"><i class="fas fa-shopping-cart"></i></a>
            </a>
        </div>
        {% endfor %}
    </div>
</section>

<section class="pagination">
    <button class="btn1"><i class="fa-solid fa-arrow-left"></i>
        <a class="previous-next-link" href="{% if products.has_previous %}
        ?{% change_params page=products.previous_page_number %}{% else %}?{% change_params page=1 %}{% endif %}">Previous</a>
    </button>
    <ul>
        {% for page in products.paginator.page_range %}
        {% if page >= products.number|add:-3 and page <= products.number|add:+3 %}
        <a class="page-selector" href="?{% change_params page=page %}">
            <li class="link {% if products.number == page %} active {% endif %}">{{ page }}</li>
        </a>
        {% endif %}
        {% endfor %}
    </ul>
    <button class="btn2"><a class="previous-next-link" href="{% if products.has_next %}
        ?{% change_params page=products.next_page_number %}
        {% else %}?{% change_params page=products.number %}{% endif %}">Next</a><i class="fa-solid fa-arrow-right"></i>
    </button>
</section>

<script src="https://cdn.jsdelivr.net/npm/nouislider@15.6.0/dist/nouislider.min.js"></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var selected_min_price = {{ selected_min_price }};
        var selected_max_price = {{ selected_max_price }};
        var minPrice = {{ min_price }}
        var maxPrice = {{ max_price }}

        var priceSlider = document.getElementById('price-range');
        noUiSlider.create(priceSlider, {
            start: [selected_min_price, selected_max_price],
            connect: true,
            range: {
                'min': minPrice,
                'max': maxPrice
            },
            step: 1,
            tooltips: false,
        });

        priceSlider.noUiSlider.on('update', function (values, handle) {
            document.getElementById('price-min').textContent = values[0];
            document.getElementById('price-max').textContent = values[1];

            document.getElementById('min-price').value = values[0];
            document.getElementById('max-price').value = values[1];
        });
    });
</script>

<script>
document.addEventListener('DOMContentLoaded', function () {
    const filterButton = document.getElementById('filterButton');
    const filterMenu = document.getElementById('filterMenu');
    const applyButton = document.querySelector('.btn-apply');

    function toggleMenu() {
        if (filterMenu.style.display === 'block') {
            filterMenu.style.display = 'none';
        } else {
            filterMenu.style.display = 'block';
        }
    }

    filterButton.addEventListener('click', function (event) {
        event.stopPropagation();
        toggleMenu();
    });

    document.addEventListener('click', function (event) {
        if (!filterMenu.contains(event.target) && event.target !== filterButton) {
            filterMenu.style.display = 'none';
        }
    });

    applyButton.addEventListener('click', function () {
        filterMenu.style.display = 'none';
    });
});
</script>

{% endblock %}

clothesshop/clothes/templates/clothes/product.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/product.css' %}">{% endblock %}

{% block title %}{{title}}{% endblock %}

{% block content%}

<section class="product-info">
    <div class="product-images">
        <div class="single-product-image">
            <img class="main-image" src="{{ product.image.url }}" width="100%" alt="">
        </div>

        <div class="small-product-images">
            {% for image in product.images.all %}
            <div class="small-img-row">
                <img class="small-img {% if forloop.first %}active{% endif %}" src="{{ image.image.url }}"
                     data-index="0" width="100%" alt="">
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="product-details">
        <h6>{{ product.brand }}</h6>
        <h4>{{ product.name }}</h4>
        {% if product.discount %}
        <div class="discount">
            <h2>{{ product.sell_price }} RUB</h2>
            <h2 class="original-price">{{ product.price }} RUB</h2>
        </div>
        {% else %}
        <h2>{{ product.price }} RUB</h2>
        {% endif %}
        <div class="size-selector">
            {% for size in sizes %}
            <button type="button" class="size-button" data-size="{{ size.size }}">{{size.size}}</button>
            {% endfor %}
        </div>

        <div class="user-buttons">
            <a href="{% url 'cart:cart_add' %}" class="btn add-to-cart"
               data-product-id="{{ product.id }}">{% csrf_token %}Add To Cart</a>
            <button class="favorite-btn">Favorites<i class="fa-regular fa-heart"></i></button>
            {% if user.is_superuser %}
            <button class="btn-admin btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#editProductModal-{{ product.slug }}">
                Edit
            </button>
            <form method="post" action="{% url 'catalog:delete_product' product.slug %}" class="d-inline">
            {% csrf_token %}
                <button type="submit" class="btn-admin btn btn-danger" onclick="return confirm('Are you sure you want to delete this product?');">
                    Delete
                </button>
            </form>
            {% endif %}
        </div>
        <p>{{ product.description|linebreaks }}</p>


    </div>

    <div class="modal fade" id="editProductModal-{{ product.slug }}" tabindex="-1" aria-labelledby="editProductModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editProductModalLabel">Edit {{ product.name }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" enctype="multipart/form-data" action="{% url 'catalog:edit_product' product.slug %}">
                {% csrf_token %}
                <div class="modal-body">
                    {{ form.as_p }}
                    <h6>Additional Images</h6>
                    <input type="file" name="new_images" multiple class="form-control">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

</section>

<section class="additional-info">
    <div class="accordion">
        <div class="accordion-item">
            <button class="accordion-button">Delivery</button>
            <div class="accordion-content">
                <p>
                    Here is a description of how the shop handles delivery...
                </p>
            </div>
        </div>
        <div class="accordion-item">
            <button class="accordion-button">Payment</button>
            <div class="accordion-content">
                <p>
                    Here is a description of how the payment is made...
                </p>
            </div>
        </div>
        <div class="accordion-item">
            <button class="accordion-button">Return</button>
            <div class="accordion-content">
                <p>
                    Here is a description of how the return of goods occurs...
                </p>
            </div>
        </div>
    </div>
</section>

<script>
    const accordionButtons = document.querySelectorAll('.accordion-button');

    accordionButtons.forEach(button => {
        button.addEventListener('click', () => {
            const content = button.nextElementSibling;

            button.classList.toggle('active');

            if (button.classList.contains('active')) {
                content.style.maxHeight = content.scrollHeight + 'px';
            } else {
                content.style.maxHeight = 0;
            }
        });
    });


    const mainImage = document.querySelector('.main-image');
    const smallImages = document.querySelectorAll('.small-img');

    smallImages.forEach(function (smallImg, index) {
        smallImg.addEventListener('click', function () {
            const tempMainSrc = mainImage.src;

            mainImage.src = smallImg.src;

            for (let i = index; i > 0; i--) {
                smallImages[i].src = smallImages[i - 1].src;
            }

            smallImages[0].src = tempMainSrc;

            smallImages.forEach(img => img.classList.remove('active'));
            smallImg.classList.add('active');
        });
    });

</script>


{% endblock %}