clothesshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change_quantity/', views.cart_change_quantity, name='cart_change_quantity'),
    path('cart_change_size/', views.cart_change_size, name='cart_change_size'),
    path('cart_change_delivery/', views.cart_change_delivery, name='cart_change_delivery'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

clothesshop/clothes/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.catalog, name='catalog'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit_product/<slug:product_slug>', views.edit_product, name='edit_product'),
    path('delete_product/<slug:product_slug>', views.delete_product, name='delete_product'),
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='catalog_by_category'),
    path('product/<slug:product_slug>', views.product, name='product'),
]

clothesshop/clothesshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('clothes.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clothesshop/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('order/', views.order, name='order'),
]

clothesshop/cart/models.py
from django.db import models

from clothes.models import Products, Sizes
from users.models import User


class CartQuerySet(models.QuerySet):

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0

    def total_price_with_delivery(self):
        return sum(cart.products_price() for cart in self)

class Cart(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='User')
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE, verbose_name='Product')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Quantity')
    size = models.ForeignKey(to=Sizes, on_delete=models.CASCADE, verbose_name='Size', related_name='cart_size')
    available_sizes = models.ManyToManyField(to=Sizes, verbose_name='Available Sizes', related_name='available_sizes')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='Date added')

    class Meta:
        db_table = 'cart'
        verbose_name = 'Cart'
        verbose_name_plural = 'Carts'
        ordering = ['-id']

    objects = CartQuerySet.as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f'Cart of user {self.user.username} | Product: {self.product.brand} {self.product.name} | Quantity: {self.quantity}'

clothesshop/cart/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

from django.template.loader import render_to_string

from .models import Cart
from .utils import get_user_carts
from clothes.models import ProductSizes, Products, Sizes


def cart_add(request):
    product_id = request.POST.get('product_id')
    product = Products.objects.get(id=product_id)
    size_char = request.POST.get('size')
    print(size_char)
    size = Sizes.objects.get(size=size_char)
    available_sizes = ProductSizes.objects.filter(product_id=product_id)

    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, product=product)
        message = 'Product added to cart.'

        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            cart = Cart.objects.create(user=request.user, product=product, quantity=1, size=size)
            available_sizes_list = [product_size.size for product_size in available_sizes]
            cart.available_sizes.set(available_sizes_list)
    else:
        message = 'You are not logged in.'

    user_cart = get_user_carts(request)
    cart_items_html = render_to_string('cart/cart.html', {'carts': user_cart}, request=request)

    response_data = {
        'message': message,
        'cart_items_html': cart_items_html,
    }

    return JsonResponse(response_data)


def cart_change_quantity(request):
    cart_id = request.POST.get('cart_id')
    quantity = request.POST.get('quantity')

    cart = Cart.objects.get(id=cart_id)

    cart.quantity = quantity

    cart.save()

    user_cart = get_user_carts(request)
    cart_items_html = render_to_string('cart/cart.html', {'carts': user_cart}, request=request)

    response_data = {
        'cart_items_html': cart_items_html,
        'quantity': cart.quantity,
    }

    return JsonResponse(response_data)


def cart_change_size(request):
    cart_id = request.POST.get('cart_id')
    size_id = request.POST.get('size')
    print(size_id)

    size = Sizes.objects.get(id=size_id)

    cart = Cart.objects.get(id=cart_id)

    cart.size = size

    cart.save()

    user_cart = get_user_carts(request)
    cart_items_html = render_to_string('cart/cart.html', {'carts': user_cart}, request=request)

    response_data = {
        'cart_items_html': cart_items_html,
        'size': cart.size.size,
    }

    return JsonResponse(response_data)


def cart_change_delivery(request):
    user_cart = get_user_carts(request)

    products_price = user_cart.total_price()
    delivery_type = request.POST.get('delivery_type')

    if delivery_type == 'express':
        delivery_price = 500
    else:
        delivery_price = 0

    total_price = products_price + delivery_price
    user_cart.total_price_with_delivery = total_price

    cart_html = render_to_string('cart/cart.html', {'carts': user_cart, 'delivery_type': delivery_type, 'delivery_price': delivery_price,}, request=request)

    response_data = {
        'delivery_type': delivery_type,
        'cart_html': cart_html,
        'delivery_price': delivery_price,
        'total_price': user_cart.total_price_with_delivery,
    }

    return JsonResponse(response_data)


def cart_remove(request):
    cart_id = request.POST.get('cart_id')

    cart = Cart.objects.get(id=cart_id)
    quantity = cart.quantity
    cart.delete()

    user_cart = get_user_carts(request)
    cart_items_html = render_to_string('cart/cart.html', {'carts': user_cart}, request=request)

    response_data = {
        'message': 'Product removed from cart.',
        'cart_items_html': cart_items_html,
        'quantity_deleted' : quantity,
    }

    return JsonResponse(response_data)

clothesshop/cart/templates/cart/cart.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/cart.css' %}">


<div class="cart-container" id="cart-items-container">
    <div class="cart-card">
        <div class="cart-row row">
            <div class="cart-col-md-8 cart-items col-md-8">
                <div class="cart-title">
                    <div class="cart-row row">
                        <div class="cart-col col"><h4><b>Shopping Cart</b></h4></div>
                    </div>
                </div>
                <div class="header-row row">
                    <div class="header-image col">Image</div>
                    <div class="header-product col">Product</div>
                    <div class="header-quantity col">Quantity</div>
                    <div class="header-size col">Size</div>
                    <div class="header-price col">Price</div>
                    <div class="header-remove col"></div>
                </div>
                {% for cart in carts %}
                <div class="cart-row row border-top border-bottom">
                    <div class="cart-row row main align-items-center">
                        <div class="cart-col-2 col-2"><img class="cart-img-fluid" src="{{ cart.product.image.url }}"></div>
                        <div class="cart-col col">
                            <div class="cart-row row text-muted" style="padding-left: 25px">{{ cart.product.brand }}</div>
                            <div class="cart-row row" style="padding-left: 25px">{{ cart.product.name }}</div>
                        </div>
                        <div class="quantity-change cart-col col">
                            <a href="{% url 'cart:cart_change_quantity' %}" class="decrement btn" data-cart-id="{{ cart.id }}" data-quantity-change-url="{% url 'cart:cart_change_quantity' %}">
                            {% csrf_token %}-
                            </a>
                            <input type="text" class="number" value="{{ cart.quantity }}">
                            <a href="{% url 'cart:cart_change_quantity' %}" class="increment btn" data-cart-id="{{ cart.id }}" data-quantity-change-url="{% url 'cart:cart_change_quantity' %}">
                            {% csrf_token %}+
                            </a>
                        </div>
                        <div class="item-size col">
                            <select class="size-selector" data-cart-id="{{ cart.id }}" data-size-change-url="{% url 'cart:cart_change_size' %}">
                                {% for size in cart.available_sizes.all %}
                                <option data-size-id="{{ size.id }}" value="{{ size.id }}" {% if size.id == cart.size.id %}selected{% endif %}>
                                {{ size.size }}
                                </option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="cart-col col" style="padding-left: 50px">{% if cart.quantity == 1 %}{{ cart.product.sell_price }}
                            {% else %}{{ cart.products_price }}{% endif %}RUB</div>
                        <div class="remove-item col"><a href="{% url 'cart:cart_remove' %}" class="remove-from-cart"
                        data-cart-id="{{ cart.id }}">{% csrf_token %}<i class="fa-regular fa-circle-xmark"></i></a></div>
                    </div>
                </div>
                {% endfor %}
                <div class="cart-back-to-shop"><a href="{% url 'catalog:catalog' %}">&leftarrow;</a><span class="text-muted">Back to shop</span></div>
            </div>
            <div class="cart-col-md-4 cart-summary col-md-4">
                <div><h5><b>Summary</b></h5></div>
                <hr>
                <div class="cart-row row">
                    <div class="cart-col col" style="padding-left:0;">Products</div>
                    <div class="cart-col text-right col">{{ carts.total_price }} RUB</div>
                </div>
                <div class="cart-row row">
                    <div class="cart-col col" style="padding-left:0;">Delivery</div>
                    <div class="cart-col text-right col" id="delivery-price"> RUB</div>
                </div>
                <form class="cart-form">
                    <p>DELIVERY</p>
                    <select class="delivery-selector" id="delivery-type" data-change-delivery-url="{% url 'cart:cart_change_delivery' %}">
                        <option value="standard" class="text-muted">Standard Delivery - FREE</option>
                        <option value="express" class="text-muted" {% if carts.total_price_with_delivery > carts.total_price %}selected{% endif %}>
                            Express-Delivery - 500 RUB</option>
                    </select>
                    <p>GIVE CODE</p>
                    <input class="promo-input" id="cart-code" placeholder="Enter your code">
                </form>
                <div class="cart-row row" style="border-top: 1px solid rgba(0,0,0,.1); padding: 2vh 0;">
                    <div class="cart-col col">TOTAL PRICE</div>
                    <div class="cart-col text-right col" id="total-price">{{ carts.total_price_with_delivery }} RUB</div>
                </div>
                <a href="{% url 'orders:order' %}" class="cart-btn btn">CHECKOUT</a>
            </div>
        </div>
    </div>
</div>